# Datasource configuration in dev environment
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/IOT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5