# Datasource configuration in dev environment
spring:
  jpa:
    show-sql: false
    hibernate:
      default_schema: public
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    generate-ddl: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5130/iot
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0ct4ld4t4b4s3*!=+++@
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
